packages:
  - name: bot
    environment:
      SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"
      SLACK_SIGNING_SECRET: "${SLACK_SIGNING_SECRET}"
      GRAZIE_JWT_TOKEN: "${GRAZIE_JWT_TOKEN}"
      MAKE_WEBHOOK_URL: "${MAKE_WEBHOOK_URL}"
    functions:
      - name: post_papers
        runtime: python:3.9
        web: false
        limits:
          timeout: 900000
          memory: 256
        triggers:
          - name: post
            sourceType: scheduler
            sourceDetails:
              cron: "0 8 * * *"
      - name: handle_interactions
        runtime: python:3.9
        web: raw
        limits:
          memory: 256
